spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    base-url: http://localhost:9411   # changed from host.docker.internal
    enabled: true

  sleuth:
    sampler:
      probability: 1.0
    propagation-keys:
      - b3
      - X-B3-TraceId
      - X-B3-SpanId
      - X-B3-ParentSpanId
      - X-B3-Sampled
      - X-B3-Flags
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %5p [${spring.application.name},%X{traceId},%X{spanId}] %logger{36} - %msg%n"
resilience4j.retry:
  instances:
    kafkaRetry:
      maxAttempts: 3
      waitDuration: 2s

resilience4j.circuitbreaker:
  instances:
    kafkaPublisher:
      failureRateThreshold: 50
      slidingWindowSize: 10
      waitDurationInOpenState: 30s

resilience4j:
  retry:
    instances:
      productServiceRetry:
        max-attempts: 3
        wait-duration: 2s
  circuitbreaker:
    instances:
      productServiceCB:
        failure-rate-threshold: 50
        sliding-window-size: 10
        wait-duration-in-open-state: 10s			
logging:
  level:
    io.github.resilience4j.retry: DEBUG
    org.springframework.cloud.openfeign: DEBUG
